window.STAATI_PRESENTATION = {
  brand: {
    name: "STAATI",
    accentColor: "#526CF4",
    organizationName: "Target Organization",
    presenterName: "Presenter Name",
    companyName: "STAATI",
    website: "staati.unventured.ai",
    email: "hello@staati.com",
    phone: "+965 0000 0000",
  },
  slides: [
    {
      id: "cover",
      number: 1,
      theme: "dark",
      type: "cover",
      label: { en: "B2B · Sports Health Technology · GCC", ar: "B2B · تقنية الصحة الرياضية · الخليج" },
      title: { en: "STAATI", ar: "ستاتي" },
      subtitle: { en: "The Sports Rehabilitation Operating System", ar: "نظام متكامل لإدارة التأهيل الرياضي" },
      body: { en: "From injury to return.\nOne platform. Every athlete.", ar: "من لحظة الإصابة إلى العودة للملاعب.\nمنصة واحدة. لكل رياضي." },
      notes: { en: "Confidential Presentation", ar: "عرض سري" },
    },
    {
      id: "opening-scenario",
      number: 2,
      theme: "dark",
      type: "timeline",
      label: { en: "Opening Scenario", ar: "المشهد الافتتاحي" },
      title: { en: "A first-team player is injured.\nWhat happens next?", ar: "أُصيب أحد لاعبي الفريق الأول.\nماذا يحدث بعد ذلك؟" },
      subtitle: { en: "Every recovery begins as a chain of decisions across people, places and evidence.", ar: "كل رحلة تعافٍ تبدأ كسلسلة قرارات بين أشخاص ومواقع وأدلة." },
      bullets: {
        en: ["Injury", "Assessment", "Imaging", "Treatment", "Rehabilitation", "Performance Testing", "Medical Clearance", "Return to Sport"],
        ar: ["الإصابة", "التقييم", "التصوير الطبي", "العلاج", "التأهيل", "اختبارات الأداء", "التصريح الطبي", "العودة للمنافسة"],
      },
    },
    {
      id: "todays-reality",
      number: 3,
      theme: "light",
      type: "fragmented",
      label: { en: "Today's Reality", ar: "واقع اليوم" },
      title: { en: "The athlete’s recovery is spread across disconnected tools.", ar: "رحلة تعافي اللاعب موزعة بين أدوات وأنظمة منفصلة." },
      body: { en: "Different records.\nDifferent versions.\nNo single source of truth.", ar: "سجلات مختلفة.\nنسخ مختلفة.\nولا يوجد مصدر موحد للحقيقة." },
      bullets: {
        en: ["WhatsApp", "Spreadsheets", "PDF files", "Paper records", "Email", "Notes", "Phone calls", "Images and videos"],
        ar: ["واتساب", "جداول", "ملفات PDF", "سجلات ورقية", "البريد", "ملاحظات", "مكالمات", "صور وفيديوهات"],
      },
    },
    {
      id: "business-impact",
      number: 4,
      theme: "light",
      type: "bullets",
      label: { en: "Business Impact", ar: "الأثر التشغيلي" },
      title: { en: "Fragmented rehabilitation creates operational and medical risk.", ar: "تشتت بيانات التأهيل يخلق مخاطر تشغيلية وطبية." },
      bullets: {
        en: ["Delayed rehabilitation decisions.", "Incomplete medical documentation.", "Poor coordination between doctors, physiotherapists and coaches.", "Limited visibility for management.", "Difficulty proving return-to-play readiness.", "Lost athlete availability.", "Repeated tests and duplicated work."],
        ar: ["تأخر قرارات التأهيل.", "نقص التوثيق الطبي.", "ضعف التنسيق بين الطبيب والأخصائي والجهاز الفني.", "غياب الرؤية الواضحة للإدارة.", "صعوبة إثبات جاهزية اللاعب للعودة.", "خسارة أيام مشاركة اللاعب.", "تكرار الاختبارات والعمل."],
      },
    },
    {
      id: "introducing-staati",
      number: 5,
      theme: "dark",
      type: "statement",
      label: { en: "Introducing STAATI", ar: "تعريف ستاتي" },
      title: { en: "One record.\nOne timeline.\nEvery decision documented.", ar: "سجل واحد.\nمسار زمني واحد.\nكل قرار موثق." },
      body: { en: "STAATI connects the athlete, physiotherapist, doctor, coach and sports organization through one structured rehabilitation record.", ar: "تربط ستاتي الرياضي وأخصائي العلاج الطبيعي والطبيب والمدرب والمنظمة الرياضية ضمن سجل تأهيلي واحد ومنظم." },
    },
    {
      id: "complete-journey",
      number: 6,
      theme: "dark",
      type: "journey",
      label: { en: "Complete Journey", ar: "رحلة متكاملة" },
      title: { en: "From injury to clearance, one connected journey.", ar: "من الإصابة إلى التصريح، رحلة واحدة مترابطة." },
      bullets: {
        en: ["Injury", "Clinical Intake", "Diagnosis", "Treatment Plan", "Rehabilitation Program", "Daily Athlete Check-ins", "Performance Tests", "Return-to-Play Gates", "Medical Sign-Off", "Return to Competition"],
        ar: ["الإصابة", "فتح الملف السريري", "التشخيص", "خطة العلاج", "برنامج التأهيل", "المتابعة اليومية", "اختبارات الأداء", "مراحل العودة للملاعب", "الاعتماد الطبي", "العودة للمنافسة"],
      },
    },
    {
      id: "multiple-experiences",
      number: 7,
      theme: "light",
      type: "layers",
      label: { en: "Platform Architecture", ar: "هيكل المنصة" },
      title: { en: "One platform.\nBuilt for the entire sports organization.", ar: "منصة واحدة.\nمصممة لجميع أطراف المنظمة الرياضية." },
      bullets: {
        en: ["Athlete Mobile App", "Medical & Physiotherapy Portal", "Club Management Dashboard"],
        ar: ["تطبيق الرياضي", "بوابة الفريق الطبي والعلاج الطبيعي", "لوحة إدارة النادي"],
      },
      notes: { en: "Unified Athlete Record", ar: "السجل الموحد للرياضي" },
    },
    {
      id: "athlete-experience",
      number: 8,
      theme: "dark",
      type: "athlete",
      label: { en: "Athlete Experience", ar: "تجربة الرياضي" },
      title: { en: "Their day.\nTheir session.\nYour protocol.", ar: "يومه.\nجلسته.\nخطة فريقك الطبي." },
      body: { en: "Athletes see only what they need today, while the medical team sees the full rehabilitation journey.", ar: "يرى الرياضي ما يحتاج إليه اليوم فقط، بينما يطّلع الفريق الطبي على رحلة التأهيل كاملة." },
      bullets: {
        en: ["Today's session", "Daily check-in", "Rehabilitation program", "Progress", "Coach communication", "Return-to-play milestones"],
        ar: ["جلسة اليوم", "المتابعة اليومية", "برنامج التأهيل", "التقدم", "تواصل المدرب", "مراحل العودة للملاعب"],
      },
      images: ["assets/screenshots/home-rest.jpg", "assets/screenshots/daily-log.jpg", "assets/screenshots/program.jpg"],
    },
    {
      id: "medical-workspace",
      number: 9,
      theme: "light",
      type: "workspace",
      label: { en: "Concept Interface", ar: "واجهة تصورية" },
      title: { en: "The operating system for the sports medical team.", ar: "نظام العمل المتكامل للفريق الطبي الرياضي." },
      bullets: {
        en: ["Athlete roster", "Clinical intake", "Injury records", "Exercise program builder", "Treatment notes", "Test results", "Attachments", "Reports", "Signatures", "Return-to-play gates"],
        ar: ["قائمة الرياضيين", "فتح الملف السريري", "سجلات الإصابة", "بناء برنامج التمارين", "ملاحظات العلاج", "نتائج الاختبارات", "المرفقات", "التقارير", "التوقيعات", "مراحل العودة"],
      },
    },
    {
      id: "daily-checkins",
      number: 10,
      theme: "dark",
      type: "checkins",
      label: { en: "Daily Signals", ar: "الإشارات اليومية" },
      title: { en: "Know how every athlete is responding — every day.", ar: "اعرف استجابة كل رياضي لبرنامج التأهيل، يومياً." },
      body: { en: "Small daily signals become a meaningful rehabilitation story.", ar: "الإشارات اليومية البسيطة تتحول إلى صورة واضحة لمسار التأهيل." },
      metrics: {
        en: ["Pain", "Mood", "Sleep", "Energy", "Soreness", "Readiness"],
        ar: ["الألم", "المزاج", "النوم", "الطاقة", "الإجهاد", "الجاهزية"],
      },
      images: ["assets/screenshots/daily-log.jpg", "assets/screenshots/home-progress.jpg"],
    },
    {
      id: "structured-programs",
      number: 11,
      theme: "light",
      type: "programs",
      label: { en: "Structured Programs", ar: "برامج منظمة" },
      title: { en: "Programs built week by week.\nDelivered day by day.", ar: "برامج تُبنى أسبوعاً بعد أسبوع.\nوتُنفذ يوماً بعد يوم." },
      body: { en: "The medical team controls the full protocol.\nThe athlete sees today’s session.", ar: "الفريق الطبي يدير الخطة كاملة.\nوالرياضي يرى جلسة اليوم." },
      bullets: {
        en: ["Warm-up", "Main session", "Mobility", "Strength", "Conditioning", "Cool-down", "Video instructions", "Completion status"],
        ar: ["الإحماء", "الجلسة الرئيسية", "الحركة", "القوة", "اللياقة", "التهدئة", "تعليمات فيديو", "حالة الإنجاز"],
      },
      images: ["assets/screenshots/program.jpg"],
    },
    {
      id: "rtp-gates",
      number: 12,
      theme: "dark",
      type: "gates",
      label: { en: "Return-to-Play Gates", ar: "مراحل العودة للملاعب" },
      title: { en: "Return-to-play should be a documented decision — not an assumption.", ar: "العودة للملاعب يجب أن تكون قراراً موثقاً، لا مجرد تقدير." },
      bullets: {
        en: ["Pain-free movement", "Range of motion", "Strength symmetry", "Jump testing", "Sport-specific movement", "Psychological readiness", "Full team training", "Medical approval"],
        ar: ["حركة بدون ألم", "مدى الحركة", "تماثل القوة", "اختبار القفز", "حركة خاصة بالرياضة", "الجاهزية النفسية", "تدريب كامل مع الفريق", "الاعتماد الطبي"],
      },
    },
    {
      id: "communication",
      number: 13,
      theme: "light",
      type: "communication",
      label: { en: "Communication", ar: "التواصل" },
      title: { en: "Every conversation stays connected to the athlete’s record.", ar: "كل محادثة تبقى مرتبطة بسجل الرياضي." },
      bullets: {
        en: ["Athlete messages physiotherapist.", "Physiotherapist adds note.", "Doctor reviews progress.", "Coach receives approved readiness status.", "Management sees operational overview."],
        ar: ["الرياضي يراسل أخصائي العلاج.", "الأخصائي يضيف ملاحظة.", "الطبيب يراجع التقدم.", "المدرب يستلم حالة الجاهزية المعتمدة.", "الإدارة ترى الملخص التشغيلي."],
      },
      images: ["assets/screenshots/messages.jpg", "assets/screenshots/profile.jpg"],
    },
    {
      id: "value",
      number: 14,
      theme: "dark",
      type: "benefits",
      label: { en: "Club Value", ar: "قيمة للنادي" },
      title: { en: "Built for better clinical decisions and stronger sports operations.", ar: "مصممة لتحسين القرارات السريرية وكفاءة العمليات الرياضية." },
      bullets: {
        en: ["Standardized rehabilitation.", "Complete athlete medical history.", "Better communication.", "Clear return-to-play accountability.", "Centralized reporting.", "Greater visibility across squads and departments."],
        ar: ["توحيد إجراءات التأهيل.", "سجل طبي متكامل للرياضي.", "تحسين التواصل.", "وضوح مسؤولية قرار العودة.", "تقارير مركزية.", "رؤية شاملة للفرق والأقسام."],
      },
    },
    {
      id: "organizations",
      number: 15,
      theme: "light",
      type: "organizations",
      label: { en: "Organizations", ar: "المنظمات" },
      title: { en: "Designed for modern sports organizations.", ar: "مصممة للمنظمات الرياضية الحديثة." },
      bullets: {
        en: ["Professional sports clubs", "National teams", "Sports federations", "Olympic committees", "Youth academies", "Sports medicine centers", "Physiotherapy clinics", "Corporate athlete programs"],
        ar: ["الأندية الرياضية المحترفة", "المنتخبات الوطنية", "الاتحادات الرياضية", "اللجان الأولمبية", "أكاديميات الناشئين", "مراكز الطب الرياضي", "عيادات العلاج الطبيعي", "برامج الرياضيين للشركات"],
      },
    },
    {
      id: "enterprise",
      number: 16,
      theme: "dark",
      type: "enterprise",
      label: { en: "Enterprise Deployment", ar: "التطبيق المؤسسي" },
      title: { en: "Adaptable to the structure of your organization.", ar: "قابلة للتكيّف مع هيكل منظمتكم." },
      bullets: {
        en: ["Multiple teams and squads", "Multiple sports", "Role-based access", "Club branding", "Arabic and English", "Organization-wide reporting", "Custom rehabilitation protocols", "Data migration support", "Onboarding and training", "Enterprise support"],
        ar: ["فرق وتشكيلات متعددة", "رياضات متعددة", "صلاحيات حسب الدور", "هوية النادي", "العربية والإنجليزية", "تقارير على مستوى المنظمة", "بروتوكولات تأهيل مخصصة", "دعم نقل البيانات", "التدريب والتهيئة", "دعم مؤسسي"],
      },
      notes: { en: "White-label options available subject to agreement.", ar: "خيارات العلامة البيضاء متاحة حسب الاتفاق." },
    },
    {
      id: "pilot",
      number: 17,
      theme: "light",
      type: "pilot",
      label: { en: "Pilot Program", ar: "برنامج تجريبي" },
      title: { en: "Start with one team.\nProve the model.\nScale across the organization.", ar: "ابدأ بفريق واحد.\nأثبت النموذج.\nثم توسع عبر المنظمة." },
      bullets: {
        en: ["Week 1: Discovery and workflow mapping.", "Week 2: Platform setup and medical team onboarding.", "Weeks 3–8: Live pilot with selected athletes.", "End of pilot: Review adoption, documentation quality and operational outcomes."],
        ar: ["الأسبوع 1: اكتشاف سير العمل ورسمه.", "الأسبوع 2: إعداد المنصة وتهيئة الفريق الطبي.", "الأسابيع 3-8: تجربة مباشرة مع رياضيين محددين.", "نهاية التجربة: مراجعة التبني وجودة التوثيق والنتائج التشغيلية."],
      },
      metrics: {
        en: ["Athlete adoption", "Daily check-in completion", "Program completion", "Documentation completeness", "Medical team usage", "Return-to-play record quality"],
        ar: ["تبني الرياضيين", "اكتمال المتابعة اليومية", "إنجاز البرنامج", "اكتمال التوثيق", "استخدام الفريق الطبي", "جودة سجل العودة"],
      },
    },
    {
      id: "product-overview",
      number: 18,
      theme: "dark",
      type: "productOverview",
      label: { en: "Product Overview", ar: "نظرة عامة على المنتج" },
      kicker: { en: "Prepared by Designed Studio · June 2026", ar: "إعداد Designed Studio · يونيو 2026" },
      title: {
        en: "The complete platform for sports rehabilitation.",
        ar: "منصة متكاملة لإدارة التأهيل الرياضي.",
      },
      body: {
        en: "From the moment an athlete is injured to the moment they are cleared, STAATI connects assessments, programs, scheduling, daily check-ins, clearance and communication in one system.",
        ar: "من لحظة إصابة الرياضي إلى لحظة التصريح بالعودة، تربط ستاتي التقييمات والبرامج والجدولة والمتابعة اليومية والتصريح والتواصل في نظام واحد.",
      },
      bullets: {
        en: ["Assessments", "Training programs", "Scheduling", "Daily check-ins", "Return-to-play clearance", "Communication", "iOS athlete app"],
        ar: ["التقييمات", "برامج التدريب", "الجدولة", "المتابعة اليومية", "تصريح العودة للملاعب", "التواصل", "تطبيق iOS للرياضي"],
      },
      meta: {
        en: [
          { label: "Prepared for", value: "The STAATI team" },
          { label: "Status", value: "Live in production" },
          { label: "Website", value: "staati.unventured.ai" },
          { label: "Region", value: "Kuwait / GCC" },
        ],
        ar: [
          { label: "مقدم إلى", value: "فريق STAATI" },
          { label: "الحالة", value: "Live in production" },
          { label: "الموقع", value: "staati.unventured.ai" },
          { label: "المنطقة", value: "الكويت / الخليج" },
        ],
      },
    },
    {
      id: "five-parts",
      number: 19,
      theme: "light",
      type: "partsMap",
      label: { en: "The Five Parts", ar: "الأجزاء الخمسة" },
      title: { en: "Five connected surfaces. One athlete record.", ar: "خمس واجهات مترابطة. سجل رياضي واحد." },
      body: {
        en: "Each user gets the workspace they need while privacy and data ownership remain clear.",
        ar: "كل مستخدم يحصل على الواجهة المناسبة له، مع وضوح الخصوصية وملكية البيانات.",
      },
      parts: {
        en: [
          { title: "The Website", audience: "Prospective coaches and clinics", summary: "Public site, sign-up, pricing and trial." },
          { title: "Coach Workspace", audience: "Individual coaches", summary: "Manage athletes and recovery workflows." },
          { title: "For Clinics", audience: "Clinics with several coaches", summary: "Oversight, seats, invitations and reassignment." },
          { title: "Athlete App", audience: "Athletes on iOS", summary: "Programs, check-ins, messaging and progress." },
          { title: "Administration", audience: "The STAATI team", summary: "Internal service operations and controls." },
        ],
        ar: [
          { title: "الموقع", audience: "المدربون والعيادات المحتملة", summary: "تعريف المنتج، التسجيل، الأسعار والتجربة." },
          { title: "مساحة المدرب", audience: "المدرب الفردي", summary: "إدارة الرياضيين ومسار التعافي." },
          { title: "للعيادات", audience: "عيادات تضم عدة مدربين", summary: "إشراف، مقاعد، دعوات ونقل رياضيين." },
          { title: "تطبيق الرياضي", audience: "الرياضيون على iOS", summary: "برامج، متابعة يومية، تواصل وتقدم." },
          { title: "الإدارة", audience: "فريق STAATI", summary: "تشغيل الخدمة والتحكم الداخلي." },
        ],
      },
      notes: {
        en: [
          "A coach sees only their own athletes.",
          "Clinics add oversight without changing the coach workflow.",
          "Athletes never see professional tools, only their own program.",
        ],
        ar: [
          "المدرب يرى الرياضيين التابعين له فقط.",
          "العيادة تضيف طبقة إشراف بدون تغيير طريقة عمل المدرب.",
          "الرياضي لا يرى أدوات المحترفين، فقط برنامجه الخاص.",
        ],
      },
    },
    {
      id: "website-surface",
      number: 20,
      theme: "dark",
      type: "capability",
      label: { en: "The Website", ar: "الموقع" },
      title: { en: "The public entry point for coaches and clinics.", ar: "نقطة الدخول العامة للمدربين والعيادات." },
      body: {
        en: "The website introduces STAATI, explains pricing, and lets new users begin a 14-day trial without a credit card.",
        ar: "الموقع يعرّف بستاتي، يوضح الأسعار، ويمكّن المستخدمين من بدء تجربة 14 يوماً بدون بطاقة.",
      },
      link: { en: "Visit the website", ar: "زيارة الموقع" },
      sections: {
        en: [
          { title: "Landing page", label: "Welcome", items: ["Product story", "Return-to-play case study", "Responsive desktop and mobile"] },
          { title: "Pricing", label: "Plans", items: ["Free tier", "Per-coach plan", "Flat clinic plan priced per coach"] },
          { title: "Conversion", label: "Trial", items: ["14-day trial", "No credit card required", "Privacy and Terms pages"] },
        ],
        ar: [
          { title: "صفحة تعريفية", label: "Welcome", items: ["قصة المنتج", "حالة عودة للملاعب", "متجاوبة على الجوال والكمبيوتر"] },
          { title: "الأسعار", label: "Plans", items: ["خطة مجانية", "خطة لكل مدرب", "خطة ثابتة للعيادة محسوبة حسب المدربين"] },
          { title: "التحويل", label: "Trial", items: ["تجربة 14 يوماً", "بدون بطاقة", "صفحات الخصوصية والشروط"] },
        ],
      },
    },
    {
      id: "coach-workspace-deep",
      number: 21,
      theme: "light",
      type: "capability",
      label: { en: "Coach Workspace", ar: "مساحة المدرب" },
      title: { en: "Where a coach manages every athlete's recovery.", ar: "حيث يدير المدرب رحلة تعافي كل رياضي." },
      body: {
        en: "The workspace combines athlete profiles, clinical assessments, programs, day-to-day care, monitoring and messaging.",
        ar: "تجمع مساحة المدرب ملفات الرياضيين، التقييمات السريرية، البرامج، الرعاية اليومية، المتابعة والتواصل.",
      },
      link: { en: "Coach sign-in", ar: "دخول المدرب" },
      sections: {
        en: [
          { title: "Athletes & teams", label: "Roster", items: ["Searchable roster", "Athlete profile", "Teams and squads"] },
          { title: "Assessments", label: "Clinical", items: ["Intake history", "Joint-by-joint examination", "8-stage return-to-play checklist"] },
          { title: "Training", label: "Programs", items: ["Multi-week builder", "Exercise library", "Assign by start date"] },
          { title: "Day-to-day care", label: "Care", items: ["Scheduling", "Daily wellness check-ins", "Treatments log and performance testing"] },
          { title: "Monitoring", label: "Signal", items: ["Weekly dashboard", "Needs-attention feed", "Return-to-play board"] },
          { title: "Communication", label: "Account", items: ["Messaging with push notifications", "Profile settings", "Plan management"] },
        ],
        ar: [
          { title: "الرياضيون والفرق", label: "Roster", items: ["قائمة قابلة للبحث", "ملف الرياضي", "فرق وتشكيلات"] },
          { title: "التقييمات", label: "Clinical", items: ["تاريخ الإصابة", "فحص مفصل حسب الجسم والمفاصل", "قائمة عودة للملاعب من 8 مراحل"] },
          { title: "التدريب", label: "Programs", items: ["بناء برامج متعددة الأسابيع", "مكتبة تمارين", "تعيين البرنامج بتاريخ بداية"] },
          { title: "الرعاية اليومية", label: "Care", items: ["جدولة الجلسات", "متابعة يومية للصحة", "سجل العلاجات واختبارات الأداء"] },
          { title: "المتابعة", label: "Signal", items: ["لوحة أسبوعية", "تنبيهات تحتاج متابعة", "لوحة العودة للملاعب"] },
          { title: "التواصل", label: "Account", items: ["رسائل مع إشعارات", "إعدادات الملف", "إدارة الخطة"] },
        ],
      },
    },
    {
      id: "clinic-layer",
      number: 22,
      theme: "dark",
      type: "capability",
      label: { en: "For Clinics", ar: "للعيادات" },
      title: { en: "An oversight layer for clinics with multiple coaches.", ar: "طبقة إشراف للعيادات التي تضم عدة مدربين." },
      body: {
        en: "Clinics keep each coach's workspace private while owners and admins manage the team, seats and athlete assignments.",
        ar: "تحافظ العيادة على خصوصية مساحة كل مدرب، بينما يدير المالكون والمشرفون الفريق والمقاعد وتوزيع الرياضيين.",
      },
      link: { en: "Clinic sign-in", ar: "دخول العيادة" },
      sections: {
        en: [
          { title: "Clinic setup", label: "Owner", items: ["Create a clinic", "Become owner", "Invite coaches by email"] },
          { title: "Team oversight", label: "Dashboard", items: ["Active coaches", "Pending invitations", "Seats in use"] },
          { title: "Roster control", label: "Athletes", items: ["Clinic-wide client list", "Coach tags", "Reassign individually or in bulk"] },
          { title: "Operations", label: "Control", items: ["Activate or deactivate coaches", "Hand departing athletes to another coach", "Clinic-level billing"] },
        ],
        ar: [
          { title: "إعداد العيادة", label: "Owner", items: ["إنشاء عيادة", "تعيين المالك", "دعوة المدربين بالبريد"] },
          { title: "إشراف الفريق", label: "Dashboard", items: ["المدربون النشطون", "الدعوات المعلقة", "المقاعد المستخدمة"] },
          { title: "التحكم بالقائمة", label: "Athletes", items: ["قائمة عملاء على مستوى العيادة", "وسم كل رياضي بمدربه", "إعادة التعيين فردياً أو جماعياً"] },
          { title: "التشغيل", label: "Control", items: ["تفعيل أو تعطيل المدربين", "نقل رياضيي المدرب المغادر", "فوترة على مستوى العيادة"] },
        ],
      },
    },
    {
      id: "athlete-app-deep",
      number: 23,
      theme: "light",
      type: "capability",
      label: { en: "Athlete App", ar: "تطبيق الرياضي" },
      title: { en: "The athlete only sees what they need to follow the program.", ar: "الرياضي يرى فقط ما يحتاجه لتنفيذ البرنامج." },
      body: {
        en: "The iOS app keeps athletes focused on today's work, logging, check-ins, messaging and recovery milestones.",
        ar: "تطبيق iOS يركز الرياضي على عمل اليوم، تسجيل التمارين، المتابعة اليومية، الرسائل ومراحل التعافي.",
      },
      link: { en: "See the app", ar: "عرض التطبيق" },
      sections: {
        en: [
          { title: "Access", label: "Sign-in", items: ["Email sign-in", "Coach-provided code", "Onboarding background and goals"] },
          { title: "Program delivery", label: "Workout", items: ["Today's workout or rest day", "Full program by week and day", "Demo videos"] },
          { title: "Logging", label: "Check-ins", items: ["Mark exercises done", "Log sets, reps and loads", "Daily wellness check-ins"] },
          { title: "Connection", label: "Progress", items: ["Messaging with push notifications", "Recovery progress", "Return-to-play milestones and coach profile"] },
        ],
        ar: [
          { title: "الدخول", label: "Sign-in", items: ["تسجيل بالبريد", "كود من المدرب", "تهيئة الخلفية والأهداف"] },
          { title: "توصيل البرنامج", label: "Workout", items: ["تمرين اليوم أو يوم راحة", "برنامج كامل حسب الأسبوع واليوم", "فيديوهات شرح"] },
          { title: "التسجيل", label: "Check-ins", items: ["تحديد التمارين المنجزة", "تسجيل الجولات والتكرارات والأوزان", "متابعة يومية للصحة"] },
          { title: "الارتباط", label: "Progress", items: ["رسائل مع إشعارات", "تقدم التعافي", "مراحل العودة وملف المدرب"] },
        ],
      },
    },
    {
      id: "admin-console",
      number: 24,
      theme: "dark",
      type: "capability",
      label: { en: "Platform Administration", ar: "إدارة المنصة" },
      title: { en: "The internal console for running the service.", ar: "لوحة داخلية لتشغيل الخدمة." },
      body: {
        en: "The STAATI team gets a console for coach management, subscriptions, exercise content, announcements and feature controls.",
        ar: "يحصل فريق ستاتي على لوحة لإدارة المدربين والاشتراكات ومحتوى التمارين والإعلانات والتحكم بالميزات.",
      },
      link: { en: "Admin sign-in", ar: "دخول الإدارة" },
      sections: {
        en: [
          { title: "Business overview", label: "Metrics", items: ["Coaches", "Athletes", "Subscriptions"] },
          { title: "Coach management", label: "Accounts", items: ["Plans and statuses", "Account actions", "Subscription overview"] },
          { title: "Content operations", label: "Library", items: ["Shared exercise catalogue", "Announcements", "In-app messages"] },
          { title: "Controls", label: "Feature flags", items: ["Switch capabilities on or off", "Roll out clinic features per account", "Activity log"] },
        ],
        ar: [
          { title: "نظرة الأعمال", label: "Metrics", items: ["المدربون", "الرياضيون", "الاشتراكات"] },
          { title: "إدارة المدربين", label: "Accounts", items: ["الخطط والحالات", "إجراءات الحساب", "نظرة الاشتراكات"] },
          { title: "تشغيل المحتوى", label: "Library", items: ["كتالوج التمارين المشترك", "الإعلانات", "رسائل داخل التطبيق"] },
          { title: "التحكم", label: "Feature flags", items: ["تشغيل أو إيقاف الميزات", "إطلاق ميزات العيادات حسب الحساب", "سجل النشاط"] },
        ],
      },
    },
    {
      id: "system-glance",
      number: 25,
      theme: "light",
      type: "benefits",
      label: { en: "At a Glance", ar: "لمحة سريعة" },
      title: { en: "The system at a glance.", ar: "النظام في لمحة." },
      bullets: {
        en: [
          "One connected system across assessments, programs, check-ins, scheduling, testing and messaging.",
          "Private by design for coaches, clinics and athletes.",
          "Clinical foundation for assessment and return-to-play decisions.",
          "Web for professionals and administrators; iOS for athletes.",
          "Regional foundation with KD pricing for Kuwait and GCC.",
          "Roadmap includes in-app payments and expanded communications.",
        ],
        ar: [
          "نظام واحد يربط التقييمات والبرامج والمتابعة والجدولة والاختبارات والرسائل.",
          "خصوصية مصممة للمدربين والعيادات والرياضيين.",
          "أساس سريري للتقييم وقرارات العودة للملاعب.",
          "الويب للمحترفين والإدارة، وiOS للرياضيين.",
          "أساس إقليمي وتسعير بالدينار الكويتي للكويت والخليج.",
          "خارطة الطريق تشمل الدفع داخل التطبيق وتوسيع التواصل.",
        ],
      },
    },
    {
      id: "closing",
      number: 18,
      theme: "dark",
      type: "closing",
      label: { en: "Closing", ar: "الختام" },
      title: { en: "Every recovery deserves one trusted record.", ar: "كل رحلة تعافٍ تستحق سجلاً موثوقاً واحداً." },
      body: { en: "Let’s build the digital rehabilitation infrastructure for your athletes.", ar: "لنُنشئ معاً البنية الرقمية لتأهيل رياضييكم." },
      cta: { en: "Request an Enterprise Demonstration", ar: "اطلب عرضاً مخصصاً للمنشآت الرياضية" },
    },
  ],
};
