window.STAATI_PRESENTATION = {
  brand: {
    name: "STAATI",
    accentColor: "#526CF4",
    organizationName: "Target Organization",
    presenterName: "Presenter Name",
    companyName: "STAATI",
    website: "staati.unventured.ai",
    email: "hello@staati.com",
    phone: "+965 0000 0000",
  },
  slides: [
    {
      id: "cover",
      number: 1,
      theme: "dark",
      type: "cover",
      label: { en: "B2B · Sports Health Technology · GCC", ar: "B2B · تقنية الصحة الرياضية · الخليج" },
      title: { en: "STAATI", ar: "ستاتي" },
      subtitle: { en: "The Coach Dashboard for Sports Rehabilitation", ar: "لوحة المدرب لإدارة التأهيل الرياضي" },
      body: { en: "Manage athletes, programs, check-ins and return-to-play decisions.\nOne workspace for every recovery.", ar: "إدارة الرياضيين والبرامج والمتابعة وقرارات العودة للملاعب.\nمساحة عمل واحدة لكل رحلة تعافٍ." },
      notes: { en: "Confidential Presentation", ar: "عرض سري" },
    },
    {
      id: "opening-scenario",
      number: 2,
      theme: "dark",
      type: "timeline",
      label: { en: "Opening Scenario", ar: "المشهد الافتتاحي" },
      title: { en: "A first-team player is injured.\nWhat happens next?", ar: "أُصيب أحد لاعبي الفريق الأول.\nماذا يحدث بعد ذلك؟" },
      subtitle: { en: "Every recovery begins as a chain of decisions across people, places and evidence.", ar: "كل رحلة تعافٍ تبدأ كسلسلة قرارات بين أشخاص ومواقع وأدلة." },
      bullets: {
        en: ["Injury", "Assessment", "Imaging", "Treatment", "Rehabilitation", "Performance Testing", "Medical Clearance", "Return to Sport"],
        ar: ["الإصابة", "التقييم", "التصوير الطبي", "العلاج", "التأهيل", "اختبارات الأداء", "التصريح الطبي", "العودة للمنافسة"],
      },
    },
    {
      id: "todays-reality",
      number: 3,
      theme: "light",
      type: "fragmented",
      label: { en: "Today's Reality", ar: "واقع اليوم" },
      title: { en: "The athlete’s recovery is spread across disconnected tools.", ar: "رحلة تعافي اللاعب موزعة بين أدوات وأنظمة منفصلة." },
      body: { en: "Different records.\nDifferent versions.\nNo single source of truth.", ar: "سجلات مختلفة.\nنسخ مختلفة.\nولا يوجد مصدر موحد للحقيقة." },
      bullets: {
        en: ["WhatsApp", "Spreadsheets", "PDF files", "Paper records", "Email", "Notes", "Phone calls", "Images and videos"],
        ar: ["واتساب", "جداول", "ملفات PDF", "سجلات ورقية", "البريد", "ملاحظات", "مكالمات", "صور وفيديوهات"],
      },
    },
    {
      id: "business-impact",
      number: 4,
      theme: "light",
      type: "bullets",
      label: { en: "Business Impact", ar: "الأثر التشغيلي" },
      title: { en: "Fragmented rehabilitation creates operational and medical risk.", ar: "تشتت بيانات التأهيل يخلق مخاطر تشغيلية وطبية." },
      bullets: {
        en: ["Delayed rehabilitation decisions.", "Incomplete medical documentation.", "Poor coordination between doctors, physiotherapists and coaches.", "Limited visibility for management.", "Difficulty proving return-to-play readiness.", "Lost athlete availability.", "Repeated tests and duplicated work."],
        ar: ["تأخر قرارات التأهيل.", "نقص التوثيق الطبي.", "ضعف التنسيق بين الطبيب والأخصائي والجهاز الفني.", "غياب الرؤية الواضحة للإدارة.", "صعوبة إثبات جاهزية اللاعب للعودة.", "خسارة أيام مشاركة اللاعب.", "تكرار الاختبارات والعمل."],
      },
    },
    {
      id: "introducing-staati",
      number: 5,
      theme: "dark",
      type: "statement",
      label: { en: "Introducing STAATI", ar: "تعريف ستاتي" },
      title: { en: "One record.\nOne timeline.\nEvery decision documented.", ar: "سجل واحد.\nمسار زمني واحد.\nكل قرار موثق." },
      body: { en: "STAATI gives coaches and therapists one workspace to manage every athlete’s rehabilitation record, daily status, program, tests and return-to-play decision.", ar: "تمنح ستاتي المدرب والمعالج مساحة واحدة لإدارة سجل التأهيل، الحالة اليومية، البرنامج، الاختبارات وقرار العودة لكل رياضي." },
    },
    {
      id: "complete-journey",
      number: 6,
      theme: "dark",
      type: "journey",
      label: { en: "Complete Journey", ar: "رحلة متكاملة" },
      title: { en: "From injury to clearance, one connected journey.", ar: "من الإصابة إلى التصريح، رحلة واحدة مترابطة." },
      bullets: {
        en: ["Injury", "Clinical Intake", "Diagnosis", "Treatment Plan", "Rehabilitation Program", "Daily Athlete Check-ins", "Performance Tests", "Return-to-Play Gates", "Medical Sign-Off", "Return to Competition"],
        ar: ["الإصابة", "فتح الملف السريري", "التشخيص", "خطة العلاج", "برنامج التأهيل", "المتابعة اليومية", "اختبارات الأداء", "مراحل العودة للملاعب", "الاعتماد الطبي", "العودة للمنافسة"],
      },
    },
    {
      id: "multiple-experiences",
      number: 7,
      theme: "light",
      type: "layers",
      label: { en: "Platform Architecture", ar: "هيكل المنصة" },
      title: { en: "One coach workspace.\nConnected to the athlete experience.", ar: "مساحة عمل واحدة للمدرب.\nمرتبطة بتجربة الرياضي." },
      bullets: {
        en: ["Coach Dashboard", "Athlete Mobile App", "Organization Visibility"],
        ar: ["لوحة المدرب", "تطبيق الرياضي", "رؤية للمنظمة"],
      },
      notes: { en: "Coach-led rehabilitation record", ar: "سجل تأهيلي يقوده المدرب" },
    },
    {
      id: "coach-dashboard",
      number: 8,
      theme: "dark",
      type: "coachDashboard",
      label: { en: "Coach Dashboard", ar: "لوحة المدرب" },
      title: { en: "The coach starts every day with what needs attention.", ar: "يبدأ المدرب يومه بما يحتاج متابعة." },
      body: {
        en: "STAATI turns the coach’s daily work into one command center: active athletes, sessions, check-ins, RTP gates and the next actions to take.",
        ar: "تحول ستاتي عمل المدرب اليومي إلى مركز قيادة واحد: الرياضيون النشطون، الجلسات، المتابعات، مراحل العودة والخطوات التالية.",
      },
      bullets: {
        en: ["Needs-attention queue", "Weekly overview", "Fast actions for intake, programs and sessions", "Search across clients, programs and actions"],
        ar: ["قائمة تحتاج متابعة", "نظرة أسبوعية", "إجراءات سريعة للملف والبرنامج والجلسات", "بحث بين العملاء والبرامج والإجراءات"],
      },
      image: "assets/dashboard/coach-dashboard.png",
      alt: { en: "STAATI coach dashboard home", ar: "واجهة لوحة المدرب في ستاتي" },
    },
    {
      id: "coach-roster",
      number: 9,
      theme: "light",
      type: "dashboardFeature",
      label: { en: "Roster & Teams", ar: "الرياضيون والفرق" },
      title: { en: "Manage the people first: athletes, squads and conversations.", ar: "إدارة الأشخاص أولاً: الرياضيون، الفرق والمحادثات." },
      body: {
        en: "The coach sees who is under care, how athletes are grouped, and which conversations are active without jumping between tools.",
        ar: "يرى المدرب من هم تحت رعايته، وكيف يتم توزيعهم على الفرق، وأي المحادثات نشطة بدون التنقل بين أدوات متفرقة.",
      },
      bullets: {
        en: ["Athlete roster with teams and sessions", "Squads for group management", "One message list for the coach’s roster", "Every conversation stays tied to the athlete"],
        ar: ["قائمة رياضيين مع الفرق والجلسات", "فرق لإدارة المجموعات", "قائمة رسائل واحدة لروستر المدرب", "كل محادثة مرتبطة بسجل الرياضي"],
      },
      images: [
        { src: "assets/dashboard/athletes.png", label: { en: "Athlete roster", ar: "قائمة الرياضيين" } },
        { src: "assets/dashboard/teams.png", label: { en: "Teams", ar: "الفرق" } },
        { src: "assets/dashboard/messages.png", label: { en: "Messages", ar: "الرسائل" } },
      ],
    },
    {
      id: "coach-programming",
      number: 10,
      theme: "dark",
      type: "dashboardFeature",
      label: { en: "Training Operations", ar: "تشغيل التدريب" },
      title: { en: "Build programs once. Assign, schedule and adapt them day by day.", ar: "ابنِ البرامج مرة. عيّنها وجدولها وعدّلها يومياً." },
      body: {
        en: "Programs, exercise library and calendar scheduling live in the same coach workspace, so rehab plans become operational instead of theoretical.",
        ar: "البرامج ومكتبة التمارين والجدولة تعيش في مساحة المدرب نفسها، فتتحول خطة التأهيل من نظرية إلى تشغيل يومي.",
      },
      bullets: {
        en: ["Multi-week programs", "Exercise library by muscle and category", "Session calendar", "Fast program assignment"],
        ar: ["برامج متعددة الأسابيع", "مكتبة تمارين حسب العضلة والفئة", "تقويم للجلسات", "تعيين سريع للبرامج"],
      },
      images: [
        { src: "assets/dashboard/programs.png", label: { en: "Programs", ar: "البرامج" } },
        { src: "assets/dashboard/library.png", label: { en: "Exercise library", ar: "مكتبة التمارين" } },
        { src: "assets/dashboard/schedule.png", label: { en: "Schedule", ar: "الجدولة" } },
      ],
    },
    {
      id: "coach-recovery-workflow",
      number: 11,
      theme: "light",
      type: "dashboardFeature",
      label: { en: "Health & Recovery", ar: "الصحة والتعافي" },
      title: { en: "Document care from check-in to treatment to assessment.", ar: "توثيق الرعاية من المتابعة إلى العلاج إلى التقييم." },
      body: {
        en: "Daily readiness, treatment modalities and clinical assessments sit beside the athlete’s program, giving the coach and therapist a real timeline.",
        ar: "الجاهزية اليومية، وسائل العلاج، والتقييمات السريرية بجانب برنامج الرياضي، لتكوين مسار زمني حقيقي للمدرب والمعالج.",
      },
      bullets: {
        en: ["Wellness check-ins", "Treatment logs by modality and body part", "Intake and clinical exam history", "Return-to-play checklist"],
        ar: ["متابعة يومية للصحة", "سجلات علاج حسب الوسيلة والمنطقة", "تاريخ الملف والتقييم السريري", "قائمة تحقق للعودة للملاعب"],
      },
      images: [
        { src: "assets/dashboard/checkins.png", label: { en: "Check-ins", ar: "المتابعات" } },
        { src: "assets/dashboard/treatments.png", label: { en: "Treatments", ar: "العلاجات" } },
        { src: "assets/dashboard/assessments.png", label: { en: "Assessments", ar: "التقييمات" } },
      ],
    },
    {
      id: "coach-performance-evidence",
      number: 12,
      theme: "dark",
      type: "dashboardFeature",
      label: { en: "Performance Evidence", ar: "أدلة الأداء" },
      title: { en: "Return-to-play becomes a visible decision trail.", ar: "قرار العودة يصبح مساراً واضحاً بالأدلة." },
      body: {
        en: "The coach can track performance tests, athlete progress and RTP gates in one place before clearing the next step.",
        ar: "يستطيع المدرب متابعة اختبارات الأداء، تقدم الرياضي، ومراحل العودة في مكان واحد قبل اعتماد الخطوة التالية.",
      },
      bullets: {
        en: ["Performance test library and results", "Per-athlete 28-day progress snapshots", "RTP gate status", "Evidence before clearance"],
        ar: ["مكتبة اختبارات ونتائج أداء", "لقطات تقدم لكل رياضي خلال 28 يوماً", "حالة مراحل العودة", "أدلة قبل التصريح"],
      },
      images: [
        { src: "assets/dashboard/tests.png", label: { en: "Tests", ar: "الاختبارات" } },
        { src: "assets/dashboard/progress.png", label: { en: "Progress", ar: "التقدم" } },
        { src: "assets/dashboard/rtp.png", label: { en: "Return-to-play", ar: "العودة للملاعب" } },
      ],
    },
    {
      id: "athlete-experience",
      number: 8,
      theme: "dark",
      type: "athlete",
      label: { en: "Client Side", ar: "جانب العميل" },
      title: { en: "The athlete app supports the coach’s plan.", ar: "تطبيق الرياضي يخدم خطة المدرب." },
      body: { en: "The client or patient sees the daily session and check-in only. The coach keeps the full clinical and performance context.", ar: "العميل أو المريض يرى جلسة اليوم والمتابعة فقط. المدرب يحتفظ بالسياق السريري والأدائي الكامل." },
      bullets: {
        en: ["Today's session", "Daily check-in", "Rehabilitation program", "Progress", "Coach communication", "Return-to-play milestones"],
        ar: ["جلسة اليوم", "المتابعة اليومية", "برنامج التأهيل", "التقدم", "تواصل المدرب", "مراحل العودة للملاعب"],
      },
      images: ["assets/screenshots/home-rest.jpg", "assets/screenshots/daily-log.jpg", "assets/screenshots/program.jpg"],
    },
    {
      id: "medical-workspace",
      number: 9,
      theme: "light",
      type: "workspace",
      label: { en: "Coach Workspace", ar: "مساحة المدرب" },
      title: { en: "A structured workspace for the coach and therapist.", ar: "مساحة منظمة للمدرب والمعالج." },
      bullets: {
        en: ["Athlete roster", "Teams", "Messages", "Program builder", "Exercise library", "Schedule", "Check-ins", "Treatments", "Assessments", "Return-to-play gates"],
        ar: ["قائمة الرياضيين", "الفرق", "الرسائل", "بناء البرامج", "مكتبة التمارين", "الجدولة", "المتابعات", "العلاجات", "التقييمات", "مراحل العودة"],
      },
    },
    {
      id: "daily-checkins",
      number: 10,
      theme: "dark",
      type: "checkins",
      label: { en: "Daily Signals", ar: "الإشارات اليومية" },
      title: { en: "The coach sees readiness signals before the session.", ar: "يرى المدرب مؤشرات الجاهزية قبل الجلسة." },
      body: { en: "Pain, mood, sleep and energy help the coach adapt the day’s workload instead of guessing.", ar: "الألم، المزاج، النوم والطاقة تساعد المدرب على تعديل حمل اليوم بدون تخمين." },
      metrics: {
        en: ["Pain", "Mood", "Sleep", "Energy", "Soreness", "Readiness"],
        ar: ["الألم", "المزاج", "النوم", "الطاقة", "الإجهاد", "الجاهزية"],
      },
      images: ["assets/screenshots/daily-log.jpg", "assets/screenshots/home-progress.jpg"],
    },
    {
      id: "structured-programs",
      number: 11,
      theme: "light",
      type: "programs",
      label: { en: "Structured Programs", ar: "برامج منظمة" },
      title: { en: "Programs built week by week.\nControlled by the coach.", ar: "برامج تُبنى أسبوعاً بعد أسبوع.\nوتبقى تحت تحكم المدرب." },
      body: { en: "The coach builds and assigns the protocol. The athlete receives the right session at the right time.", ar: "يبني المدرب البروتوكول ويعيّنه. والرياضي يستلم الجلسة المناسبة في الوقت المناسب." },
      bullets: {
        en: ["Warm-up", "Main session", "Mobility", "Strength", "Conditioning", "Cool-down", "Video instructions", "Completion status"],
        ar: ["الإحماء", "الجلسة الرئيسية", "الحركة", "القوة", "اللياقة", "التهدئة", "تعليمات فيديو", "حالة الإنجاز"],
      },
      images: ["assets/screenshots/program.jpg"],
    },
    {
      id: "rtp-gates",
      number: 12,
      theme: "dark",
      type: "gates",
      label: { en: "Return-to-Play Gates", ar: "مراحل العودة للملاعب" },
      title: { en: "The coach can prove readiness before clearance.", ar: "يستطيع المدرب إثبات الجاهزية قبل التصريح." },
      bullets: {
        en: ["Pain-free movement", "Range of motion", "Strength symmetry", "Jump testing", "Sport-specific movement", "Psychological readiness", "Full team training", "Medical approval"],
        ar: ["حركة بدون ألم", "مدى الحركة", "تماثل القوة", "اختبار القفز", "حركة خاصة بالرياضة", "الجاهزية النفسية", "تدريب كامل مع الفريق", "الاعتماد الطبي"],
      },
    },
    {
      id: "communication",
      number: 13,
      theme: "light",
      type: "communication",
      label: { en: "Communication", ar: "التواصل" },
      title: { en: "Coach-athlete communication stays inside the record.", ar: "تواصل المدرب والرياضي يبقى داخل السجل." },
      bullets: {
        en: ["Athlete messages the coach or therapist.", "Coach reviews the message beside check-ins.", "Treatment or program updates are documented.", "RTP status stays visible.", "Management sees only the approved overview."],
        ar: ["الرياضي يراسل المدرب أو المعالج.", "المدرب يراجع الرسالة بجانب المتابعات.", "تحديثات العلاج أو البرنامج يتم توثيقها.", "حالة العودة تبقى واضحة.", "الإدارة ترى الملخص المعتمد فقط."],
      },
      images: ["assets/screenshots/messages.jpg", "assets/screenshots/profile.jpg"],
    },
    {
      id: "value",
      number: 14,
      theme: "dark",
      type: "benefits",
      label: { en: "Coach Value", ar: "قيمة للمدرب" },
      title: { en: "Built for coaches who need clinical structure and daily speed.", ar: "مصممة للمدربين الذين يحتاجون تنظيماً سريرياً وسرعة يومية." },
      bullets: {
        en: ["Faster daily decisions.", "Complete athlete history.", "Clear program ownership.", "Better coach-athlete communication.", "Documented return-to-play accountability.", "Reports when the organization needs visibility."],
        ar: ["قرارات يومية أسرع.", "تاريخ كامل للرياضي.", "ملكية واضحة للبرنامج.", "تواصل أفضل بين المدرب والرياضي.", "مسؤولية موثقة لقرار العودة.", "تقارير عند حاجة المنظمة للرؤية."],
      },
    },
    {
      id: "organizations",
      number: 15,
      theme: "light",
      type: "organizations",
      label: { en: "Organizations", ar: "المنظمات" },
      title: { en: "Designed for coaches, therapists and the organizations around them.", ar: "مصممة للمدربين والمعالجين والجهات التي تعمل حولهم." },
      bullets: {
        en: ["Professional sports clubs", "National teams", "Sports federations", "Olympic committees", "Youth academies", "Sports medicine centers", "Physiotherapy clinics", "Corporate athlete programs"],
        ar: ["الأندية الرياضية المحترفة", "المنتخبات الوطنية", "الاتحادات الرياضية", "اللجان الأولمبية", "أكاديميات الناشئين", "مراكز الطب الرياضي", "عيادات العلاج الطبيعي", "برامج الرياضيين للشركات"],
      },
    },
    {
      id: "enterprise",
      number: 16,
      theme: "dark",
      type: "enterprise",
      label: { en: "Enterprise Deployment", ar: "التطبيق المؤسسي" },
      title: { en: "The coach workflow stays focused, even when the organization scales.", ar: "يبقى عمل المدرب مركزاً حتى مع توسع المنظمة." },
      bullets: {
        en: ["Multiple teams and squads", "Multiple sports", "Role-based access", "Club branding", "Arabic and English", "Organization-wide reporting", "Custom rehabilitation protocols", "Data migration support", "Onboarding and training", "Enterprise support"],
        ar: ["فرق وتشكيلات متعددة", "رياضات متعددة", "صلاحيات حسب الدور", "هوية النادي", "العربية والإنجليزية", "تقارير على مستوى المنظمة", "بروتوكولات تأهيل مخصصة", "دعم نقل البيانات", "التدريب والتهيئة", "دعم مؤسسي"],
      },
      notes: { en: "White-label options available subject to agreement.", ar: "خيارات العلامة البيضاء متاحة حسب الاتفاق." },
    },
    {
      id: "pilot",
      number: 17,
      theme: "light",
      type: "pilot",
      label: { en: "Pilot Program", ar: "برنامج تجريبي" },
      title: { en: "Start with one coach or one team.\nProve the workflow.\nThen scale.", ar: "ابدأ بمدرب واحد أو فريق واحد.\nأثبت سير العمل.\nثم توسع." },
      bullets: {
        en: ["Week 1: Map the coach’s real workflow.", "Week 2: Set up roster, programs, assessments and RTP templates.", "Weeks 3–8: Live pilot with selected athletes.", "End of pilot: Review coach usage, documentation quality and athlete response."],
        ar: ["الأسبوع 1: رسم سير عمل المدرب الحقيقي.", "الأسبوع 2: إعداد القائمة والبرامج والتقييمات وقوالب العودة.", "الأسابيع 3-8: تجربة مباشرة مع رياضيين محددين.", "نهاية التجربة: مراجعة استخدام المدرب وجودة التوثيق واستجابة الرياضي."],
      },
      metrics: {
        en: ["Coach adoption", "Daily check-in review", "Program completion", "Documentation completeness", "Treatment logging", "Return-to-play record quality"],
        ar: ["تبني المدرب", "مراجعة المتابعة اليومية", "إنجاز البرنامج", "اكتمال التوثيق", "تسجيل العلاجات", "جودة سجل العودة"],
      },
    },
    {
      id: "closing",
      number: 18,
      theme: "dark",
      type: "closing",
      label: { en: "Closing", ar: "الختام" },
      title: { en: "Give every coach one trusted workspace for recovery.", ar: "امنح كل مدرب مساحة موثوقة واحدة للتعافي." },
      body: { en: "STAATI connects the coach, athlete and organization around the work that actually happens every day.", ar: "تربط ستاتي المدرب والرياضي والمنظمة حول العمل الذي يحدث فعلاً كل يوم." },
      cta: { en: "Request a Coach Dashboard Demo", ar: "اطلب عرض لوحة المدرب" },
    },
  ],
};
